todo/urls.py
from django.urls import path

from .views import (
    Index,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TaskToggleView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
)


app_name = "todo"

urlpatterns = [
    path("", Index.as_view(), name="index"),
    path(
        "tasks/create/",
        TaskCreateView.as_view(),
        name="task-create",
    ),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update",
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete",
    ),
    path(
        "task/<int:pk>/toggle/",
        TaskToggleView.as_view(),
        name="task-toggle"
    ),
    path(
        "tags/",
        TagListView.as_view(),
        name="tag-list",
    ),
    path(
        "tags/create/",
        TagCreateView.as_view(),
        name="tag-create",
    ),
    path(
        "tags/<int:pk>/update/",
        TagUpdateView.as_view(),
        name="tag-update",
    ),
    path(
        "tags/<int:pk>/delete/",
        TagDeleteView.as_view(),
        name="tag-delete",
    ),
]

todolist/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls", namespace="todo")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField()
    done = models.BooleanField()
    tags = models.ManyToManyField(
        Tag,
        related_name="tasks",
    )

    class Meta:
        ordering = ["done", "created_time"]

    def __str__(self):
        return self.content

todo/forms.py
from django import forms

from .models import Task, Tag


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

    class Meta:
        model = Task
        fields = (
            "content",
            "deadline",
            "done",
            "tags",
        )
        widgets = {
            "deadline": forms.DateTimeInput(
                format=("%Y-%m-%dT%H:%M"), attrs={"type": "datetime-local"}
            )
        }

todo/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views import generic

from .forms import TaskForm
from .models import Task, Tag


class Index(generic.ListView):
    model = Task
    context_object_name = "task_list"
    template_name = "todo/index.html"
    paginate_by = 5

    queryset = Task.objects.prefetch_related("tags")


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo:index")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo:index")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo:index")


class TaskToggleView(generic.View):
    def post(self, request, *args, **kwargs):
        task = get_object_or_404(Task, pk=kwargs["pk"])

        task.done = not task.done
        task.save()

        return redirect(reverse("todo:index"))


class TagListView(generic.ListView):
    model = Tag
    content_object_name = "tag_list"
    paginate_by = 5


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo:tag-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>To Do List | {% block title %}Home{% endblock %}</title>
  <link rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
    integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
    crossorigin="anonymous"
  >
  {% load static %}
  <link rel="stylesheet" href="{% static "css/styles.css" %}">
</head>

<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">

        {% block sidebar %}
          {% include "includes/sidebar.html" %}
        {% endblock %}
      </div>

      <div class="col-sm-10">

        {% block content %}{% endblock %}

        {% if is_paginated %}
          {% block pagination %}
            {% include "includes/pagination.html" %}
          {% endblock %}
        {% endif %}

      </div>
    </div>
  </div>
</body>
</html>

templates/includes/pagination.html
<ul class="pagination">
  {% if page_obj.has_previous %}
    <li class="page-item">
      <a href="?page=1" class="page-link">&laquo; First</a>
    </li>
    <li class="page-item">
      <a href="?page={{ page_obj.previous_page_number }}" class="page-link">Prev</a>
    </li>
  {% endif %}

  <li class="page-item active">
    <span class="page-link">{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>
  </li>

  {% if page_obj.has_next %}
    <li class="page-item">
      <a href="?page={{ page_obj.next_page_number }}" class="page-link">Next</a>
    </li>
  {% endif %}
</ul>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url "todo:index" %}">Home</a></li>
  <li class="list-group-item"><a href="{% url "todo:tag-list" %}">Tags</a></li>
</ul>

templates/todo/tag_confirm_delete.html
{% extends "base.html" %}

{% block title %}
  Delete tag
{% endblock %}

{% block content %}
  <h1>Delete tag?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url "todo:tag-list" %}" class="btn btn-secondary">No</a>
  </form>
{% endblock %}

templates/todo/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}
  {{ object|yesno:"Update,Create"}} tag
{% endblock %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" class="btn btn-primary" value="Submit">
  </form>
{% endblock %}

templates/todo/tag_list.html
{% extends "base.html" %}

{% block title %}
  Tags
{% endblock %}

{% block content %}
  <h1>
    Tags
    <a href="{% url "todo:tag-create" %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h1>

  {% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for tag in tag_list %}
        <tr>
          <td>
            {{ tag.name }}
          </td>
          <td>
            <a class="btn btn-secondary d-inline" href="{% url "todo:tag-update" pk=tag.id %}">
              Update
            </a>
          </td>
          <td>
            <a class="btn btn-danger d-inline" href="{% url "todo:tag-delete" pk=tag.id %}">
              Delete
            </a>
          </td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    No tags
  {% endif %}

{% endblock %}

templates/todo/task_confirm_delete.html
{% extends "base.html" %}

{% block title %}
  Delete task
{% endblock %}

{% block content %}
  <h1>Delete task?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url "todo:index" %}" class="btn btn-secondary">No</a>
  </form>
{% endblock %}

templates/todo/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}
  {{ object|yesno:"Update,Create"}} task
{% endblock %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" class="btn btn-primary" value="Submit">
  </form>
{% endblock %}

templates/todo/task_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    <strong>TODO list</strong>
    <a href="{% url "todo:task-create" %}" class="btn btn-primary link-to-page">
      Add task
    </a>
  </h1>
  <br>

  {% for task in task_list %}
    <h4>
      <strong>
        {{ task.content }}
        {% if task.done %}
         <span class="text-success">Done</span>
        {% else %} 
         <span class="text-danger">Not done</span>
        {% endif %}
      </strong>
      <form
        method="post"
        action="{% url "todo:task-toggle" pk=task.id %}"
        class="d-inline"
        novalidate
      >
        {% csrf_token %}
        {% if task.done %}
          <input type="submit" class="btn btn-secondary link-to-page" value="Undo" />
        {% else %}
          <input type="submit" class="btn btn-success link-to-page" value="Complete" />
        {% endif %}
      </form>
    </h4>
    <p>
      Created: {{ task.created_time }}
      {% if task.deadline %}
      <span class="deadline">Deadline: {{ task.deadline }}</span>
      {% endif %}
    </p>
    <h5 class="text-muted mb-4">
      Tags: 
      {% for tag in task.tags.all %}
        {{ tag.name}} 
      {% empty %}
          None
      {% endfor %}
    </h5>
    <a href="{% url "todo:task-update" pk=task.id %}" class="d-inline btn btn-secondary">Update</a>
    <a href="{% url "todo:task-delete" pk=task.id %}" class="d-inline btn btn-danger">Delete</a>
    <hr>
  {% empty %}
    <h3>No tasks</h3>
  {% endfor %}
{% endblock %}